# Generated by Django 3.0.4 on 2022-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleCrudApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('email_status', models.CharField(max_length=122)),
            ],
        ),
    ]
