# Generated by Django 3.0.4 on 2022-04-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleCrudApp', '0003_auto_20220408_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=122),
        ),
    ]
