# Generated by Django 3.0.4 on 2022-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleCrudApp', '0005_auto_20220408_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='hash',
            field=models.CharField(default='', max_length=200),
        ),
    ]
