# Generated by Django 3.0.4 on 2022-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleCrudApp', '0006_createuser_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='email_status',
            field=models.CharField(default='', max_length=122),
        ),
    ]
